# Generated by Django 3.1.7 on 2021-03-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_board', '0002_auto_20210302_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coffee_board.product')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
