# Generated by Django 3.1.7 on 2021-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_board', '0010_auto_20210508_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/no-image.jpg', upload_to='products/'),
        ),
    ]
